### ISSUE TITLE
bug: `import * as x from "file"` deletes the file

### ISSUE THREAD

**Issue by Dimava** [line/ts-remove-unused#25]
My old codebase has lots of 
```ts
import * as foo from "./foo"
foo.bar()
```
where 
```ts
// foo/index.ts
export * from "./bar"
```
where
```ts
// foo/bar.ts
export function bar(){}
```
And it deletes everything

**Comment by Dimava** [comment]
![image](https://github.com/user-attachments/assets/3ff73b2f-c19b-4cfc-b465-e8dcca9fbd42)

**Comment by kazushisan** [comment]
@Dimava thank you! I will look into the issue

**Comment by Dimava** [comment]
test cases:
- `import * as a from "a"; f(a)`
- `import * as x from "x"; f(x.a)`
- `import * as b from "b"; f(b.v)` `export const v; export const unused`
- `import * as y from "y"; f(y.w)` `export * from "c"` `export const w; export const unused`
- `import * as y from "z"; f(z.q)` `export * from "d"; export * from "unused"` `export const q`
