### ISSUE TITLE
bug: dynamic imports aren't recognized

### ISSUE THREAD

**Issue by rafaeelaudibert** [line/ts-remove-unused#27]
My codebase has a lot of lazy loading through React using dynamic imports. 

![image](https://github.com/user-attachments/assets/1e6f9225-99ce-4c06-981e-541d61a96b4b)

`ts-remove-unused` doesn't detect them and considers the imported files to be unused. For reference, https://github.com/stauren/vite-plugin-deadfile detects them just fine.

**Comment by kazushisan** [comment]
@rafaeelaudibert I think its not limited to react.lazy but more about dynamic imports in general. thanks for reporting! will work on a fix
