### ISSUE TITLE
404 not found using npx ts-remove-unused

### ISSUE THREAD

**Issue by kewp** [line/ts-remove-unused#29]
Not sure what I'm doing wrong here?

```
> npx ts-remove-unused --check
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/ts-remove-unused - Not found
npm ERR! 404 
npm ERR! 404  'ts-remove-unused@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by manelet** [comment]
`npx @line/ts-remove-unused`

**Comment by kazushisan** [comment]
My expectations was that people would `npm i` before `npx` ing but I've learnt that's not always the case... I've changed the  example code snippets in README to `npx @line/ts-remove-unused` and I will work on the screenshot as well!

I've also published https://www.npmjs.com/package/ts-remove-unused to avoid risks.
