### ISSUE TITLE
Discussion: How do we make it faster?

### ISSUE THREAD

**Issue by steelbrain** [line/ts-remove-unused#41]
Thanks for open sourcing this project. It's really useful to run on larger projects and remove years of built up dead code.

I'm starting this thread to collect ideas on how to make it faster. I'll throw in my own idea to start the mix. I think it would be interesting to gather up a list of files, spawn a pool of workers and have them all process each one by one. This could make it scale roughly with the number of cores. It could be optimized further by making the whole pool use a single typescript language server.

Any thoughts? Thanks again for open sourcing this really useful utility!

**Comment by kazushisan** [comment]
Thanks for bringing up the topic. Definitely the next objective for this tool!

**Comment by kazushisan** [comment]
I will close this issue for now because speed has improved significantly with #44 #50 and #56
