### ISSUE TITLE
Setup of Release Notes

### ISSUE THREAD

**Issue by potato4d** [line/ts-remove-unused#8]
## About

We believe that appropriate release notes/CHANGELOG should be maintained when operating as an open source library.

Usually, this means the creation of two of the following

- Generating and updating the CHANGELOG file in the source code
- Description of the differences in the description of GitHub's Release

### Generating and updating the CHANGELOG file in the source code

This is easily accomplished by using a CLI tool such as [standard-version](https://github.com/conventional-changelog/standard-version), but it is no longer an active project.

You will need to find an alternative CLI or other alternative.

e.g.) [release-please](https://github.com/googleapis/release-please) / [CLI](https://github.com/googleapis/release-please/blob/main/docs/cli.md)

### Description of the differences in the description of GitHub's Release

It is believed that GitHub's officially provided functionality can solve this problem.

https://docs.github.com/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Comment by baby230211** [comment]
Hello @potato4d,
i recommend using [changeset](https://github.com/changesets/changesets) to auto generate CHANGELOG in this repo.

Please refer to this [link](https://github.com/changesets/changesets/blob/main/docs/automating-changesets.md) on how to integrate with CI.

**Comment by kazushisan** [comment]
In the meantime, i think that working on the second solution should be good enough!
